pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/yourusername/your-repo.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('myapp:latest', './docker')
                }
            }
        }
        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:80 myapp:latest'
            }
        }
    }
}